# Generated by Django 4.1.5 on 2023-01-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=300)),
                ('owner', models.CharField(max_length=300)),
                ('groupdescrition', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('contact', models.IntegerField(max_length=9999999999)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskname', models.CharField(max_length=300)),
                ('completionstatus', models.CharField(max_length=300)),
                ('assignedto', models.CharField(max_length=300)),
                ('taskdescription', models.CharField(max_length=300)),
                ('groupname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TaskHub.groups')),
            ],
        ),
        migrations.AddField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(to='TaskHub.user'),
        ),
    ]
