# Generated by Django 4.1.5 on 2023-01-13 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskHub', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='groupdescrition',
            new_name='groupdescription',
        ),
    ]
