# Generated by Django 4.1.5 on 2023-01-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskHub', '0002_rename_groupdescrition_groups_groupdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='members',
            field=models.ManyToManyField(related_name='groups', to='TaskHub.user'),
        ),
    ]
